/**
 * Prints the reserved-username INSERTs as SQL, for `prisma db execute`.
 *
 *   pnpm seed:reserved-usernames
 *
 * Piped rather than executed, and that is the whole point of this file being a
 * script at all. It imports only `username.util.ts`, which has no imports of its
 * own and so never touches the generated Prisma client — and that client cannot
 * be loaded outside the Nest build, because it `require`s its own internals with
 * a `.js` extension that only resolves under the bundler. Doing the insert
 * through raw SQL sidesteps that entirely, the same way `user-set-role.sh` does.
 *
 * `ON CONFLICT DO NOTHING` rather than `SKIP DUPLICATES`, because that is the
 * SQL spelling of the same idea: re-running must be safe, and must never
 * overwrite a `RELEASED` row written by somebody changing their username.
 *
 * The word list is imported, never duplicated — a second copy here would drift
 * from `RESERVED_USERNAMES` silently, and the failure would be a word that is
 * quietly claimable.
 */
import { normalizedReservedUsernames } from '../src/users/username.util';

/**
 * Escapes a value for a SQL string literal.
 *
 * The allowlist on a reserved word is `^[a-z0-9_]+$`, so nothing here can
 * contain a quote today. The escape is there anyway: this is generated SQL
 * going into a `db execute` call, and a rule that holds only because of a
 * constraint enforced in a different file is not a rule.
 */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const values = normalizedReservedUsernames()
  .map((word) => `    (${sqlString(word)}, 'RESERVED')`)
  .join(',\n');

process.stdout.write(
  [
    '-- Seeds the reserved-username table. Safe to re-run.',
    '-- Generated by scripts/seed-reserved-usernames.ts from RESERVED_USERNAMES',
    '-- in src/users/username.util.ts. Edit the list there, not here.',
    '--',
    '-- "createdAt" is deliberately not in the column list: the table declares',
    '-- DEFAULT CURRENT_TIMESTAMP, and naming it here would make Postgres expect a',
    '-- third expression per row.',
    'INSERT INTO "ReservedUsername" ("usernameLower", "reason")',
    'VALUES',
    values,
    'ON CONFLICT ("usernameLower") DO NOTHING;',
    '',
  ].join('\n'),
);
