/**
 * Refreshes one user's Clerk-owned fields from Clerk, by hand.
 *
 *   pnpm user:sync <clerk-user-id>
 *
 * Why this exists: `ClerkAuthGuard` is create-only. It provisions a user on
 * their first authenticated request and never revisits them, so `name`, `email`
 * and `imageUrl` are written *only* by the `user.updated` webhook. If that
 * webhook is not reachable — a tunnel is down, the endpoint was never registered
 * in Clerk, the signing secret is a placeholder — every update silently stops
 * landing, and the only symptom is a display name that quietly stopped
 * changing.
 *
 * This is the repair tool for that window. It is deliberately manual: an
 * automatic fix would mean a Clerk API call on the request path, which is
 * latency, rate limits and an availability coupling on every authenticated
 * request, for a field that changes a handful of times in a user's life.
 *
 * Emits SQL and hands it to `prisma db execute` rather than using the Prisma
 * client, because the generated client cannot be imported from a bare `ts-node`
 * script — it `require`s its own internals with a `.js` extension that only
 * resolves under the Nest build. Same reason `seed-reserved-usernames.ts` does
 * it, and the same reason `user-set-role.sh` avoids a TypeScript runtime.
 */
import { execFileSync } from 'node:child_process';
import { config as loadEnv } from 'dotenv';

loadEnv({ path: '.env.local' });
loadEnv({ path: '.env' });

const CLERK_API = 'https://api.clerk.com/v1';

/** Mirrors the validation in `user-set-role.sh`. */
const CLERK_ID = /^user_[A-Za-z0-9]+$/;

/**
 * Escapes a value for a SQL string literal.
 *
 * These values come from Clerk, so they are not attacker-controlled — but this
 * is generated SQL fed to `db execute`, and a rule that holds only because of
 * trust in a remote service is not a rule.
 */
function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';

  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * The display name to store, matching `display-name.util.ts` exactly.
 *
 * Duplicated rather than imported because that module imports Prisma's
 * generated client transitively, which is the thing that cannot load here. The
 * rule is two `??`s and a blank check; if it ever changes, both need to change.
 */
function displayName(user: {
  full_name: string | null;
  username: string | null;
}): string | null {
  for (const candidate of [user.full_name, user.username]) {
    if (typeof candidate === 'string' && candidate.trim().length > 0) {
      return candidate;
    }
  }

  return null;
}

async function main() {
  const id = process.argv[2] ?? '';

  if (!CLERK_ID.test(id)) {
    console.error(
      'error: argument must be a Clerk user ID like user_2abc123\n' +
        `       got: ${id || '<empty>'}`,
    );
    process.exit(1);
  }

  const secretKey = process.env['CLERK_SECRET_KEY'];

  if (!secretKey || secretKey.includes('your_secret_key')) {
    console.error(
      'error: CLERK_SECRET_KEY is not set (or is still the .env.local.example\n' +
        '       placeholder). Copy .env.local.example to .env.local first.',
    );
    process.exit(1);
  }

  const response = await fetch(`${CLERK_API}/users/${id}`, {
    headers: { Authorization: `Bearer ${secretKey}` },
  });

  if (response.status === 404) {
    console.error(`error: Clerk has no user with id ${id}`);
    process.exit(1);
  }

  if (!response.ok) {
    console.error(
      `error: Clerk API returned ${response.status} ${response.statusText}`,
    );
    process.exit(1);
  }

  const user = (await response.json()) as {
    id: string;
    full_name: string | null;
    username: string | null;
    image_url: string | null;
    primary_email_address_id: string | null;
    email_addresses: { id: string; email_address: string }[];
  };

  const email =
    user.email_addresses.find(
      (entry) => entry.id === user.primary_email_address_id,
    )?.email_address ?? user.email_addresses[0]?.email_address;

  if (!email) {
    console.error(`error: Clerk user ${id} has no email address`);
    process.exit(1);
  }

  const name = displayName(user);

  const sql = [
    `-- Refreshes Clerk-owned fields for ${id} from Clerk. Generated by`,
    '-- scripts/user-sync.ts. Safe to re-run.',
    '--',
    '-- Note: this does not create the user if they are missing locally, and',
    '-- reports that as success, the same way prisma db execute does. Check',
    '-- with: pnpm prisma studio',
    'UPDATE "User"',
    `SET name = ${sqlString(name)},`,
    `    email = ${sqlString(email)},`,
    `    "imageUrl" = ${sqlString(user.image_url)}`,
    `WHERE id = ${sqlString(id)};`,
    '',
  ].join('\n');

  if (name === null) {
    console.warn(
      '  ⚠  That Clerk user has no full name and no username, so "name" is being\n' +
        '     set to NULL. Their bylines will fall back to the handle they claimed\n' +
        '     here, which is correct — but not the same as a name.',
    );
  }

  // Run Prisma from in here rather than through a shell pipe. A pipeline runs
  // its right-hand side even when the left-hand side fails, so a validation
  // error above would still hand Prisma whatever was on stdout — including
  // dotenv's startup banner — and fail with a confusing syntax error instead of
  // the real message.
  execFileSync('pnpm', ['exec', 'prisma', 'db', 'execute', '--stdin'], {
    input: sql,
    stdio: ['pipe', 'inherit', 'inherit'],
  });

  console.log(`\nSynced ${id}.`);
  console.log(
    '  Remember: prisma db execute reports success even when no row matched.\n' +
      '  If they do not exist locally, nothing happened. Check with:\n' +
      '    pnpm prisma studio',
  );
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
